/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AppForwarder__factory } from "./AppForwarder__factory";
export { Recipient__factory } from "./Recipient__factory";
